[package]
name = "buffersizebench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Enable debuginfo for profiling
[profile.release]
debug = 1

[dependencies]
argh = "0"
nix = {version="0", features=["socket"]}

